/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    carts: Cart;
    categories: Category;
    conversations: Conversation;
    media: Media;
    messages: Message;
    'moderation-actions': ModerationAction;
    orders: Order;
    'pending-checkout-attempts': PendingCheckoutAttempt;
    products: Product;
    refunds: Refund;
    reviews: Review;
    stripe_events: StripeEvent;
    tags: Tag;
    tenants: Tenant;
    users: User;
    notifications: Notification;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      subcategories: 'categories';
    };
  };
  collectionsSelect: {
    carts: CartsSelect<false> | CartsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'moderation-actions': ModerationActionsSelect<false> | ModerationActionsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'pending-checkout-attempts': PendingCheckoutAttemptsSelect<false> | PendingCheckoutAttemptsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    refunds: RefundsSelect<false> | RefundsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    stripe_events: StripeEventsSelect<false> | StripeEventsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: string;
  buyer?: (string | null) | User;
  guestSessionId?: string | null;
  sellerTenant: string | Tenant;
  status: 'active' | 'converted' | 'abandoned' | 'archived';
  itemCount?: number | null;
  items?:
    | {
        product: string | Product;
        nameSnapshot: string;
        unitAmountCents: number;
        quantity: number;
        addedAt?: string | null;
        imageSnapshot?: (string | null) | Media;
        shippingModeSnapshot?: ('free' | 'flat' | 'calculated') | null;
        id?: string | null;
      }[]
    | null;
  currency?: 'USD' | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  username: string;
  welcomeEmailSent: boolean;
  roles?: ('super-admin' | 'user' | 'support')[] | null;
  tenants?:
    | {
        tenant: string | Tenant;
        id?: string | null;
      }[]
    | null;
  /**
   * UI preferences (e.g., dismissed banners)
   */
  uiState?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  /**
   * This is the name of the store (e.g. Jay's store), if you would like to update this please contact us.
   */
  name: string;
  /**
   * This is the subdomain of the store (e.g. [username].abandonedhobby.com), if you would like to update this please contact us.
   */
  slug: string;
  image?: (string | null) | Media;
  /**
   * Hero/cover image shown at the top of your shop and product pages.
   */
  cover?: (string | null) | Media;
  /**
   * Stripe Account ID associated with your shop
   */
  stripeAccountId: string;
  /**
   * You can not sell products until you have submitted your Stripe details.
   */
  stripeDetailsSubmitted?: boolean | null;
  /**
   * Primary owner/admin for this shop
   */
  primaryContact: string | User;
  /**
   * Where operational emails (sales, alerts) are sent
   */
  notificationEmail: string;
  /**
   * Greeting/display name for notifications
   */
  notificationName?: string | null;
  /**
   * Auto-managed count of products.
   */
  productCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  tenant: string | Tenant;
  uploadedBy?: (string | null) | User;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * List a product for sale
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  tenant?: (string | null) | Tenant;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * In USD
   */
  price: number;
  /**
   * Choose how shipping is handled. If you pick “Flat fee,” enter the amount below.
   */
  shippingMode?: ('free' | 'flat' | 'calculated') | null;
  /**
   * Only required when Shipping = Flat fee
   */
  shippingFlatFee?: number | null;
  /**
   * Pick a top-level category first.
   */
  category: string | Category;
  /**
   * Choose a subcategory (enabled after picking a category).
   */
  subcategory?: (string | null) | Category;
  tags?: (string | Tag)[] | null;
  refundPolicy?: ('30 day' | '14 day' | '7 day' | '1 day' | 'no refunds') | null;
  /**
   * Reserved for future digital content. Not currently used in the customer experience.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Check this box if you want to hide this item from the entire site. Customers who have purchased this item retain access to their purchase history.
   */
  isArchived?: boolean | null;
  /**
   * Check this box if you want to hide this item from the marketplace and only show in your personal storefront.
   */
  isPrivate?: boolean | null;
  /**
   * System flag: Abandoned Hobby auto-manages this based on product type.
   */
  trackInventory?: boolean | null;
  /**
   * How many units are currently available. Decreases automatically when buyers place orders; you can increase it when you restock.
   */
  stockQuantity: number;
  /**
   * Optional cap on units a single order can buy. Hidden from sellers for now.
   */
  maxPerOrder?: number | null;
  /**
   * Reorder to change the primary image
   */
  images?:
    | {
        image?: (string | null) | Media;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Indicates that this product has been flagged for moderation review under our marketplace guidelines.
   */
  isFlagged: boolean;
  /**
   * Select the primary reason this listing was flagged for review.
   */
  flagReason?:
    | (
        | 'spam'
        | 'scam_or_fraud'
        | 'inappropriate_or_nsfw'
        | 'prohibited_item'
        | 'misleading_or_false'
        | 'copyright_or_ip'
        | 'duplicate_listing'
        | 'other'
      )
    | null;
  /**
   * Provide more detail when the flag reason is “Other” (minimum 10 characters).
   */
  flagReasonOtherText?: string | null;
  /**
   * Internal note for support (visible only to staff). Use this to document what action was taken and why.
   */
  moderationNote?: string | null;
  /**
   * Indicates that this product has been removed for a policy violation
   */
  isRemovedForPolicy?: boolean | null;
  /**
   * Set when user flagged listing as violating standards.
   */
  flaggedAt?: string | null;
  /**
   * Set when staff marks a flagged listing as Meets standards (unflags it). Used for moderation history and reporting.
   */
  approvedAt?: string | null;
  /**
   * Set when staff selects Remove for policy. Indicates when the listing was taken down (archived + removed for policy).
   */
  removedAt?: string | null;
  /**
   * Set when staff selects Reinstate after a policy removal. Reinstatement returns the listing to a private, non-public state.
   */
  reinstatedAt?: string | null;
  moderationIntent?: {
    source: 'staff_trpc' | 'admin_ui' | 'system';
    actionType: 'approved' | 'removed' | 'reinstated';
    reason?: string;
    note?: string;
    createdAt: string;
    intentId: string;
  } | null;
  latestRemovalSummary?: {
    /**
     * Optional pointer to the ModerationAction row; may be empty
     */
    actionId?: string | null;
    intentId?: string | null;
    removedAt?: string | null;
    /**
     * Removal reason snapshot (system-written). Required when a removal summary exists.
     */
    reason?:
      | (
          | 'spam'
          | 'scam_or_fraud'
          | 'inappropriate_or_nsfw'
          | 'prohibited_item'
          | 'misleading_or_false'
          | 'copyright_or_ip'
          | 'duplicate_listing'
          | 'other'
        )
      | null;
    /**
     * Internal note snapshot (system-written).
     */
    note?: string | null;
    /**
     * ID of the authenticated staff user who performed this action. Stored to avoid joins.
     */
    actorId?: string | null;
    /**
     * Snapshot of the actor’s roles at the moment of action. Set automatically.
     */
    actorRoleSnapshot?: ('super-admin' | 'support' | 'user')[] | null;
    /**
     * Historical email snapshot at time of action.
     */
    actorEmailSnapshot?: string | null;
    /**
     * Historical username snapshot at time of action.
     */
    actorUsernameSnapshot?: string | null;
    source?: ('staff_trpc' | 'admin_ui' | 'system') | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug?: string | null;
  color?: string | null;
  parent?: (string | null) | Category;
  subcategories?: {
    docs?: (string | Category)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  products?: (string | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: string;
  product: string | Product;
  buyer: string | User;
  seller: string | User;
  roomId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  conversationId: string;
  sender: string | User;
  receiver: string | User;
  content: string;
  product?: (string | null) | Product;
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Moderation Actions
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moderation-actions".
 */
export interface ModerationAction {
  id: string;
  /**
   * Product id
   */
  product: string | Product;
  /**
   * Actions available to be taken for moderation
   */
  actionType: 'approved' | 'removed' | 'reinstated';
  /**
   * Reason used by staff for this moderation action. required for removals or reinstatements).
   */
  reason?:
    | (
        | 'spam'
        | 'scam_or_fraud'
        | 'inappropriate_or_nsfw'
        | 'prohibited_item'
        | 'misleading_or_false'
        | 'copyright_or_ip'
        | 'duplicate_listing'
        | 'other'
        | 'appeal_approved'
        | 'evidence_insufficient'
        | 'mistaken_removal'
        | 'policy_updated'
        | 'seller_remediated'
        | 'duplicate_case'
        | 'automated_false_positive'
        | 'admin_error'
      )
    | null;
  /**
   * Internal note for support (visible only to staff). Use this to document the action taken and reason why. Required for removals or reinstatements
   */
  note?: string | null;
  /**
   * The authenticated staff user who performed this action. Set automatically.
   */
  actor?: (string | null) | User;
  /**
   * Snapshot of the actor’s roles at the moment this action was performed. Set automatically.
   */
  actorRoleSnapshot?: ('super-admin' | 'support' | 'user')[] | null;
  /**
   * Historical data for email at time of action.
   */
  actorEmailSnapshot?: string | null;
  /**
   * Historical data for username at time of action.
   */
  actorUsernameSnapshot?: string | null;
  source?: ('staff_trpc' | 'admin_ui' | 'system') | null;
  /**
   * Dedupe id
   */
  intentId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  name: string;
  orderNumber: string;
  buyer: string | User;
  buyerEmail?: string | null;
  sellerTenant: string | Tenant;
  /**
   * Legacy primary product reference. The authoritative list is in `items[]`.
   */
  product: string | Product;
  currency: string;
  /**
   * The total amount paid in cents (Stripe amount_total).
   */
  total: number;
  /**
   * The Stripe account associated with the order.
   */
  stripeAccountId: string;
  /**
   * The Stripe checkout session associated with the order.
   */
  stripeCheckoutSessionId?: string | null;
  stripeEventId?: string | null;
  stripePaymentIntentId?: string | null;
  stripeChargeId?: string | null;
  shipping?: {
    name?: string | null;
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  items: {
    product: string | Product;
    nameSnapshot: string;
    unitAmount: number;
    quantity: number;
    amountSubtotal?: number | null;
    amountTax?: number | null;
    amountTotal?: number | null;
    shippingMode: 'free' | 'flat' | 'calculated';
    /**
     * Only when mode = flat
     */
    shippingFeeCentsPerUnit?: number | null;
    /**
     * quantity-applied shipping for this line
     */
    shippingSubtotalCents?: number | null;
    refundPolicy?: ('30 day' | '14 day' | '7 day' | '1 day' | 'no refunds') | null;
    returnsAcceptedThrough?: string | null;
    id?: string | null;
  }[];
  returnsAcceptedThrough?: string | null;
  status?: ('paid' | 'refunded' | 'partially_refunded' | 'canceled') | null;
  fulfillmentStatus?: ('unfulfilled' | 'shipped' | 'delivered' | 'returned') | null;
  /**
   * Set when stock was decremented
   */
  inventoryAdjustedAt?: string | null;
  /**
   * Amount of refund in cents
   */
  refundedTotalCents?: number | null;
  /**
   * Set when last refunded
   */
  lastRefundAt?: string | null;
  shipment?: {
    carrier?: ('usps' | 'ups' | 'fedex' | 'other') | null;
    trackingNumber?: string | null;
    trackingUrl?: string | null;
    shippedAt?: string | null;
    /**
     * Tracks the last notification state/key sent for this shipment
     */
    lastNotifiedKey?: string | null;
  };
  /**
   * Issue a refund for this order
   */
  refunds?: {};
  /**
   * Order-level money breakdown (all cents)
   */
  amounts?: {
    subtotalCents?: number | null;
    taxTotalCents?: number | null;
    shippingTotalCents?: number | null;
    discountTotalCents?: number | null;
    platformFeeCents?: number | null;
    stripeFeeCents?: number | null;
    sellerNetCents?: number | null;
  };
  documents?: {
    invoiceUrl?: string | null;
    receiptUrl?: string | null;
  };
  /**
   * Most recent shippedAt across shipment + shipments[]. Used for sorting/pagination.
   */
  latestShippedAt?: string | null;
  /**
   * Set when delivery is confirmed
   */
  deliveredAt?: string | null;
  /**
   * Set if order is canceled
   */
  canceledAt?: string | null;
  /**
   * Optional short note for cancellation
   */
  cancellationReason?: string | null;
  /**
   * Advanced: multi-shipment history. The most recent entry mirrors into the main `shipment`.
   */
  shipments?:
    | {
        carrier?: ('usps' | 'ups' | 'fedex' | 'other') | null;
        trackingNumber?: string | null;
        trackingUrl?: string | null;
        shippedAt?: string | null;
        items?:
          | {
              /**
               * ID of the line item in orders.items[]
               */
              orderItemId?: string | null;
              quantity?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * High-level return metadata (line-level lives in Refunds collection)
   */
  returns?: {
    rmaNumber?: string | null;
    status?: ('none' | 'requested' | 'approved' | 'in_transit' | 'received' | 'refunded' | 'rejected') | null;
  };
  reviews?: {
    hasReview?: boolean | null;
    reviewId?: (string | null) | Review;
  };
  support?: {
    /**
     * Primary buyer-seller thread for this order
     */
    conversation?: (string | null) | Conversation;
    lastBuyerViewedAt?: string | null;
  };
  /**
   * Visible to buyer and seller
   */
  buyerNotes?: string | null;
  /**
   * Internal notes visible only to seller/admin
   */
  sellerPrivateNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  description: string;
  rating: number;
  product: string | Product;
  user: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pending-checkout-attempts".
 */
export interface PendingCheckoutAttempt {
  id: string;
  attemptId: string;
  userId: string | User;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds".
 */
export interface Refund {
  id: string;
  order: string | Order;
  orderNumber: string;
  stripeRefundId: string;
  stripePaymentIntentId?: string | null;
  stripeChargeId?: string | null;
  /**
   * Cents
   */
  amount: number;
  status: 'succeeded' | 'pending' | 'failed' | 'canceled';
  reason?: ('requested_by_customer' | 'duplicate' | 'fraudulent' | 'other') | null;
  selections?:
    | (
        | {
            itemId: string;
            quantity: number;
            unitAmount?: number | null;
            amountTotal?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quantity';
          }
        | {
            itemId: string;
            amountCents: number;
            id?: string | null;
            blockName?: string | null;
            blockType: 'amount';
          }
      )[]
    | null;
  fees?: {
    restockingFeeCents?: number | null;
    refundShippingCents?: number | null;
  };
  notes?: string | null;
  idempotencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stripe_events".
 */
export interface StripeEvent {
  id: string;
  eventId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * In-app notifications for users
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  user: string | User;
  type: 'message';
  payload: {
    conversationId: string;
    sender: string | User;
    /**
     * Brief preview of the message content
     */
    excerpt?: string | null;
    /**
     * Reference to the original message that triggered this notification
     */
    messageId?: string | null;
  };
  read?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'carts';
        value: string | Cart;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'conversations';
        value: string | Conversation;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'moderation-actions';
        value: string | ModerationAction;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'pending-checkout-attempts';
        value: string | PendingCheckoutAttempt;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'refunds';
        value: string | Refund;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'stripe_events';
        value: string | StripeEvent;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  buyer?: T;
  guestSessionId?: T;
  sellerTenant?: T;
  status?: T;
  itemCount?: T;
  items?:
    | T
    | {
        product?: T;
        nameSnapshot?: T;
        unitAmountCents?: T;
        quantity?: T;
        addedAt?: T;
        imageSnapshot?: T;
        shippingModeSnapshot?: T;
        id?: T;
      };
  currency?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  color?: T;
  parent?: T;
  subcategories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  product?: T;
  buyer?: T;
  seller?: T;
  roomId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  tenant?: T;
  uploadedBy?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  conversationId?: T;
  sender?: T;
  receiver?: T;
  content?: T;
  product?: T;
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moderation-actions_select".
 */
export interface ModerationActionsSelect<T extends boolean = true> {
  product?: T;
  actionType?: T;
  reason?: T;
  note?: T;
  actor?: T;
  actorRoleSnapshot?: T;
  actorEmailSnapshot?: T;
  actorUsernameSnapshot?: T;
  source?: T;
  intentId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  name?: T;
  orderNumber?: T;
  buyer?: T;
  buyerEmail?: T;
  sellerTenant?: T;
  product?: T;
  currency?: T;
  total?: T;
  stripeAccountId?: T;
  stripeCheckoutSessionId?: T;
  stripeEventId?: T;
  stripePaymentIntentId?: T;
  stripeChargeId?: T;
  shipping?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  items?:
    | T
    | {
        product?: T;
        nameSnapshot?: T;
        unitAmount?: T;
        quantity?: T;
        amountSubtotal?: T;
        amountTax?: T;
        amountTotal?: T;
        shippingMode?: T;
        shippingFeeCentsPerUnit?: T;
        shippingSubtotalCents?: T;
        refundPolicy?: T;
        returnsAcceptedThrough?: T;
        id?: T;
      };
  returnsAcceptedThrough?: T;
  status?: T;
  fulfillmentStatus?: T;
  inventoryAdjustedAt?: T;
  refundedTotalCents?: T;
  lastRefundAt?: T;
  shipment?:
    | T
    | {
        carrier?: T;
        trackingNumber?: T;
        trackingUrl?: T;
        shippedAt?: T;
        lastNotifiedKey?: T;
      };
  refunds?: T | {};
  amounts?:
    | T
    | {
        subtotalCents?: T;
        taxTotalCents?: T;
        shippingTotalCents?: T;
        discountTotalCents?: T;
        platformFeeCents?: T;
        stripeFeeCents?: T;
        sellerNetCents?: T;
      };
  documents?:
    | T
    | {
        invoiceUrl?: T;
        receiptUrl?: T;
      };
  latestShippedAt?: T;
  deliveredAt?: T;
  canceledAt?: T;
  cancellationReason?: T;
  shipments?:
    | T
    | {
        carrier?: T;
        trackingNumber?: T;
        trackingUrl?: T;
        shippedAt?: T;
        items?:
          | T
          | {
              orderItemId?: T;
              quantity?: T;
              id?: T;
            };
        id?: T;
      };
  returns?:
    | T
    | {
        rmaNumber?: T;
        status?: T;
      };
  reviews?:
    | T
    | {
        hasReview?: T;
        reviewId?: T;
      };
  support?:
    | T
    | {
        conversation?: T;
        lastBuyerViewedAt?: T;
      };
  buyerNotes?: T;
  sellerPrivateNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pending-checkout-attempts_select".
 */
export interface PendingCheckoutAttemptsSelect<T extends boolean = true> {
  attemptId?: T;
  userId?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  description?: T;
  price?: T;
  shippingMode?: T;
  shippingFlatFee?: T;
  category?: T;
  subcategory?: T;
  tags?: T;
  refundPolicy?: T;
  content?: T;
  isArchived?: T;
  isPrivate?: T;
  trackInventory?: T;
  stockQuantity?: T;
  maxPerOrder?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  isFlagged?: T;
  flagReason?: T;
  flagReasonOtherText?: T;
  moderationNote?: T;
  isRemovedForPolicy?: T;
  flaggedAt?: T;
  approvedAt?: T;
  removedAt?: T;
  reinstatedAt?: T;
  moderationIntent?: T;
  latestRemovalSummary?:
    | T
    | {
        actionId?: T;
        intentId?: T;
        removedAt?: T;
        reason?: T;
        note?: T;
        actorId?: T;
        actorRoleSnapshot?: T;
        actorEmailSnapshot?: T;
        actorUsernameSnapshot?: T;
        source?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "refunds_select".
 */
export interface RefundsSelect<T extends boolean = true> {
  order?: T;
  orderNumber?: T;
  stripeRefundId?: T;
  stripePaymentIntentId?: T;
  stripeChargeId?: T;
  amount?: T;
  status?: T;
  reason?: T;
  selections?:
    | T
    | {
        quantity?:
          | T
          | {
              itemId?: T;
              quantity?: T;
              unitAmount?: T;
              amountTotal?: T;
              id?: T;
              blockName?: T;
            };
        amount?:
          | T
          | {
              itemId?: T;
              amountCents?: T;
              id?: T;
              blockName?: T;
            };
      };
  fees?:
    | T
    | {
        restockingFeeCents?: T;
        refundShippingCents?: T;
      };
  notes?: T;
  idempotencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  description?: T;
  rating?: T;
  product?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stripe_events_select".
 */
export interface StripeEventsSelect<T extends boolean = true> {
  eventId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  image?: T;
  cover?: T;
  stripeAccountId?: T;
  stripeDetailsSubmitted?: T;
  primaryContact?: T;
  notificationEmail?: T;
  notificationName?: T;
  productCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  username?: T;
  welcomeEmailSent?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  uiState?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  payload?:
    | T
    | {
        conversationId?: T;
        sender?: T;
        excerpt?: T;
        messageId?: T;
      };
  read?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}